################################################################################
### IMPORTS
################################################################################

import os
import streamlit as st
import pandas as pd
import numpy as np
import requests
import plotly.graph_objs as go
import smtplib

from email.mime.text import MIMEText
from datetime import datetime

from ta.trend import macd, macd_signal
from ta.volatility import bollinger_hband, bollinger_lband, average_true_range
from ta.momentum import rsi

from supabase import create_client, Client


################################################################################
### SECRET HANDLER
################################################################################

def get_secret(key, default=""):

    v = os.getenv(key)
    if v:
        return v

    try:
        return st.secrets.get(key, default)
    except:
        return default


################################################################################
### CONFIG
################################################################################

SUPABASE_URL = get_secret("SUPABASE_URL")
SUPABASE_KEY = get_secret("SUPABASE_KEY")
TWELVE_DATA_KEY = get_secret("TWELVE_DATA_KEY")

EMAIL_USER = get_secret("EMAIL_USER")
EMAIL_PASS = get_secret("EMAIL_PASS")

if not SUPABASE_URL or not SUPABASE_KEY or not TWELVE_DATA_KEY:
    st.error("Missing environment variables")
    st.stop()

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

st.set_page_config(page_title="AI Forex Trading Platform", layout="wide")


################################################################################
### SESSION STATE
################################################################################

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if "last_signals" not in st.session_state:
    st.session_state.last_signals = {}


################################################################################
### EMAIL ALERT
################################################################################

def send_trade_email(pair, signal, price, confidence, sl, tp):

    if not EMAIL_USER or not EMAIL_PASS:
        return

    subject = f"Forex Alert: {signal} {pair}"

    body = f"""
Forex Trade Signal

Pair: {pair}
Signal: {signal}

Entry Price: {price}

Stop Loss: {sl}
Take Profit: {tp}

Confidence: {confidence}

Generated by Chumcred AI Forex Platform
"""

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = EMAIL_USER
    msg["To"] = "chumcred@gmail.com"

    try:

        server = smtplib.SMTP("smtp.gmail.com",587)
        server.starttls()
        server.login(EMAIL_USER,EMAIL_PASS)
        server.send_message(msg)
        server.quit()

    except Exception as e:
        print("Email failed:",e)


################################################################################
### FETCH MARKET DATA
################################################################################

@st.cache_data(ttl=1800)
def fetch_ohlc(symbol):

    url=f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1h&outputsize=500&apikey={TWELVE_DATA_KEY}"

    r=requests.get(url)
    j=r.json()

    if "values" not in j:
        return None

    df=pd.DataFrame(j["values"])

    df=df.rename(columns={
        "datetime":"Date",
        "open":"Open",
        "high":"High",
        "low":"Low",
        "close":"Close"
    })

    df["Date"]=pd.to_datetime(df["Date"])

    for c in ["Open","High","Low","Close"]:
        df[c]=pd.to_numeric(df[c])

    df=df.sort_values("Date")

    return df


################################################################################
### INDICATORS
################################################################################

def compute_indicators(df):

    df=df.copy()

    df["RSI"]=rsi(df["Close"],14)

    df["MACD"]=macd(df["Close"])
    df["MACD_SIGNAL"]=macd_signal(df["Close"])

    df["BB_HIGH"]=bollinger_hband(df["Close"])
    df["BB_LOW"]=bollinger_lband(df["Close"])

    df["MA200"]=df["Close"].rolling(200).mean()

    df["ATR"]=average_true_range(df["High"],df["Low"],df["Close"])

    return df


################################################################################
### SIGNAL ENGINE
################################################################################

def generate_signal(df):

    last=df.iloc[-1]

    buy_score=0
    sell_score=0

    if last["Close"]>last["MA200"]:
        buy_score+=1

    if last["Close"]<last["MA200"]:
        sell_score+=1

    if last["MACD"]>last["MACD_SIGNAL"]:
        buy_score+=1

    if last["MACD"]<last["MACD_SIGNAL"]:
        sell_score+=1

    if last["RSI"]>55:
        buy_score+=1

    if last["RSI"]<45:
        sell_score+=1

    if last["Close"]>last["BB_HIGH"]:
        buy_score+=1

    if last["Close"]<last["BB_LOW"]:
        sell_score+=1

    signal="NO TRADE"

    if buy_score>=3:
        signal="BUY"

    if sell_score>=3:
        signal="SELL"

    confidence=max(buy_score,sell_score)/5

    return signal,confidence,last


################################################################################
### TRADE PLAN
################################################################################

def trade_plan(price,atr,signal):

    sl=None
    tp=None

    if signal=="BUY":
        sl=price-(1.5*atr)
        tp=price+(3*atr)

    if signal=="SELL":
        sl=price+(1.5*atr)
        tp=price-(3*atr)

    return sl,tp


################################################################################
### FOREX DASHBOARD
################################################################################

def forex_dashboard():

    st.title("AI Forex Market Scanner")

    PAIRS=[
        'EUR/USD','GBP/USD','USD/JPY','AUD/USD','USD/CAD','USD/CHF','NZD/USD',
        'EUR/JPY','GBP/JPY','EUR/GBP','EUR/AUD','EUR/CAD','EUR/NZD',
        'GBP/AUD','AUD/JPY','CAD/JPY','AUD/NZD','CHF/JPY','USD/SGD',
        'USD/HKD','XAU/USD'
    ]

    results=[]

    signals_triggered=[]

    for pair in PAIRS:

        df=fetch_ohlc(pair)

        if df is None:
            continue

        df=compute_indicators(df)

        signal,confidence,last=generate_signal(df)

        price=last["Close"]

        sl,tp=trade_plan(price,last["ATR"],signal)

        results.append({
            "Pair":pair,
            "Price":round(price,5),
            "RSI":round(last["RSI"],1),
            "Signal":signal,
            "Confidence":f"{confidence:.1%}"
        })

        if signal in ["BUY","SELL"]:

            signals_triggered.append((pair,signal,price,confidence,sl,tp))


    df_table=pd.DataFrame(results)

    st.subheader("Market Scanner")

    st.dataframe(df_table)


    ############################################################
    ### SIGNAL RANKING
    ############################################################

    strong=df_table[df_table["Signal"]!="NO TRADE"]

    if len(strong)>0:

        st.subheader("Top Opportunities")

        strong=strong.sort_values("Confidence",ascending=False)

        st.table(strong.head(5))


    ############################################################
    ### EMAIL ALERTS
    ############################################################

    for pair,signal,price,confidence,sl,tp in signals_triggered:

        signal_id=f"{pair}-{signal}"

        if st.session_state.last_signals.get(pair)!=signal:

            send_trade_email(pair,signal,price,f"{confidence:.1%}",sl,tp)

            st.session_state.last_signals[pair]=signal


    ############################################################
    ### PAIR CHART
    ############################################################

    st.markdown("---")

    pair_select=st.selectbox("Deep Analysis Pair",PAIRS)

    df=fetch_ohlc(pair_select)

    df=compute_indicators(df)

    signal,confidence,last=generate_signal(df)

    entry=last["Close"]

    sl,tp=trade_plan(entry,last["ATR"],signal)

    st.write("Signal:",signal)
    st.write("Confidence:",f"{confidence:.1%}")

    st.write("Entry:",entry)
    st.write("Stop Loss:",sl)
    st.write("Take Profit:",tp)


    fig=go.Figure()

    fig.add_trace(go.Candlestick(
        x=df["Date"],
        open=df["Open"],
        high=df["High"],
        low=df["Low"],
        close=df["Close"]
    ))

    fig.add_trace(go.Scatter(
        x=df["Date"],
        y=df["BB_HIGH"],
        name="Bollinger High"
    ))

    fig.add_trace(go.Scatter(
        x=df["Date"],
        y=df["BB_LOW"],
        name="Bollinger Low"
    ))

    st.plotly_chart(fig,use_container_width=True)


    ############################################################
    ### BACKTEST ENGINE
    ############################################################

    st.markdown("---")
    st.header("Strategy Backtest")

    wins=0
    losses=0

    for i in range(200,len(df)-5):

        sub=df.iloc[:i]

        sig,conf,last=generate_signal(sub)

        entry=last["Close"]

        future=df.iloc[i+5]["Close"]

        if sig=="BUY" and future>entry:
            wins+=1

        elif sig=="SELL" and future<entry:
            wins+=1

        elif sig in ["BUY","SELL"]:
            losses+=1


    total=wins+losses

    if total>0:

        winrate=wins/total

        col1,col2,col3,col4=st.columns(4)

        col1.metric("Trades",total)
        col2.metric("Wins",wins)
        col3.metric("Losses",losses)
        col4.metric("Win Rate",f"{winrate:.2%}")


################################################################################
### LOGIN (SIMPLIFIED)
################################################################################

if not st.session_state.logged_in:

    if st.button("Login Demo"):
        st.session_state.logged_in=True
        st.rerun()

else:

    forex_dashboard()


st.write("Support: chumcred@gmail.com")
st.write("Powered by Chumcred Limited")